### ISSUE TITLE
Refactor code (event generators, MarsCalibratedRun)

### ISSUE THREAD

**Issue by aleberti** [cta-observatory/ctapipe_io_magic#11]
Code can be refactored in order to avoid duplication and unnecessary code.

Examples:
- use `cut `directly when using `uproot.TBranch.arrays` to extract event with given trigger type
- use more meaningful names for event generators
- event generators have many parts in common, so they can be unified
- the `load_events` and the various `get_xxy_event_data` can be simplified greatly

**Comment by YoshikiOhtani** [comment]
Let me post a minor comment before I forget - I think the name of the generator should be changed like "_mono_event_generator" -> "mono_event_generator" because it is not used internally.

**Comment by aleberti** [comment]
> Let me post a minor comment before I forget - I think the name of the generator should be changed like "_mono_event_generator" -> "mono_event_generator" because it is not used internally.

Well, actually in the update to ctapipe v0.12 the generators are used internally, even the pedestal one. E.g.

```python
source = MAGICEventSource(input_url="data_file_calibrated.root")
```

will use by default the mono_event_generator of the corresponding telescope, while:

```python
source = MAGICEventSource(input_url="data_file_calibrated.root", use_pedestals=True)
```

will use the pedestal_event_generator. In this way the user does not have to select by hand the generator like before, so the right generator is selected internally. Therefore, I would prefer to leave them as internal methods.

**Comment by YoshikiOhtani** [comment]
Ah I see I didn't know that, thanks. I will change my script then.
