### ISSUE TITLE
Issue of interpolators due to only 1 drive report

### ISSUE THREAD

**Issue by YoshikiOhtani** [cta-observatory/ctapipe_io_magic#16]
Again I tried to process the following data from Cal to DL1:
/home/yoshiki.ohtani/Crab/2020_11_18/1.magic_cal_to_dl1/data/calibrated/20201119_M2_05093174.001_Y_CrabNebula-W0.40+035.root

Then I faced the following error: 

```
path = '/home/yoshiki.ohtani/Crab/2020_11_18/1.magic_cal_to_dl1/data/calibrated/' \
       '20201119_M2_05093174.001_Y_CrabNebula-W0.40+035.root'

source = MAGICEventSource(path)
generator = source._pedestal_event_generator(telescope='M2')

for i_ev, event in enumerate(generator):    

     print(event.trigger.tel[2].time)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-da0bc5cc493e> in <module>
      2 generator = source._pedestal_event_generator(telescope='M1')
      3 
----> 4 for i_ev, event in enumerate(generator):

File /home/yoshiki.ohtani/Crab/2020_11_18/1.magic_cal_to_dl1/data/calibrated/20201119_M2_05093174.001_Y_CrabNebula-W0.40+035.root has only 1 drive reports.
Interpolating events information from 1 drive reports.
Drive reports available from 2020-11-18 23:35:45.888 to 2020-11-18 23:35:45.888.
Traceback (most recent call last):
  File "magic_data_cal_to_dl1.py", line 205, in <module>
    main()
  File "magic_data_cal_to_dl1.py", line 196, in main
    magic_cal_to_dl1(args.input_file, args.output_file, config)
  File "magic_data_cal_to_dl1.py", line 78, in magic_cal_to_dl1
    for i_ev, event in enumerate(event_generator):
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magic-cta-pipe/lib/python3.7/site-packages/ctapipe_io_magic/__init__.py", line 951, in _mono_event_generator
    self.current_run = self._set_active_run(self.run_numbers)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magic-cta-pipe/lib/python3.7/site-packages/ctapipe_io_magic/__init__.py", line 689, in _set_active_run
    run['data'] = MarsCalibratedRun(self.file_, self.is_mc)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magic-cta-pipe/lib/python3.7/site-packages/ctapipe_io_magic/__init__.py", line 1258, in __init__
    uproot_file, self.is_mc, self.n_camera_pixels)
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magic-cta-pipe/lib/python3.7/site-packages/ctapipe_io_magic/__init__.py", line 1658, in load_events
    drive_mjd_unique, drive_zd_unique, fill_value="extrapolate")
  File "/fefs/aswg/workspace/yoshiki.ohtani/anaconda3/envs/magic-cta-pipe/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 562, in __init__
    "least %d entries" % minval)
ValueError: x and y arrays must have at least 2 entries
```

Actually I confirmed that the M2 subrun 001 data has only 1 drive report, and then the length of `drive_mjd_unique` and `drive_zd_unique` is 1, which is now allowed for the interpolation method.

**Comment by aleberti** [comment]
One solution would be to re-merpp the calibrated file using the information from drive reports. I checked and there are all the drive report there (at least for the run you tested, but I think it is the same for the other run I found with the same problem). But for some reason, for that run, in the .rep file from SA there is only one report for each subsystem.

**Comment by YoshikiOhtani** [comment]
Hm, I see. Actually I didn't face such issue in the past, because when running the Cal -> DL1 script I input all the subrun files simultaneously with the wild card (i.e., MAGICEventSource(input_url="./data/calibrated/*_M2_05093174.*.root"), which combined the drive reports of all subrun files and so the interpolation was possible. But as far as I understand the EventSource in ctapipe v0.12.0 only allows one data file for the input, is it correct?

**Comment by aleberti** [comment]
Exactly, in the past it was not a problem, since it was done like in MARS, stacking all the drive reports. But now with one file at a time (we are forced by ctapipe as you say), this is not possible anymore. Anyway I am trying to remerpp the files, as soon as I do it I will give you a link to it (via PM or email). Anyway, I think this should be an issue also in MARS if one processes these faulty subruns alone. I will check what happens. Also, the fact that only one report per subsystem is saved in some subruns I think is an issue to be discussed within MAGIC.

**Comment by YoshikiOhtani** [comment]
OK thank you very much! Just in case let me report that I processed the Crab Nebula data taken in the following 4 nights (Nov 19, Dec 14, 16, 23) which may be used for the analysis school, and found the following 3 subrun files which shows the interpolation error:
/home/yoshiki.ohtani/combined_analysis/real/CrabNebula/2020_11_18/1.magic_cal_to_dl1/20201119_M2_05093174.001_Y_CrabNebula-W0.40+035.root
/home/yoshiki.ohtani/combined_analysis/real/CrabNebula/2020_12_13/1.magic_cal_to_dl1/data/calibrated/20201214_M1_05093663.007_Y_CrabNebula-W0.40+215.root
/home/yoshiki.ohtani/combined_analysis/real/CrabNebula/2020_12_15/1.magic_cal_to_dl1/data/calibrated/20201216_M2_05093713.001_Y_CrabNebula-W0.40+035.root

As you said there are not so much files, but almost one subrun file per day, and so it would be better to solve anyway.

**Comment by aleberti** [comment]
Ok, I merpped again the one from 20201119. Later I will do the others. When I am done, I will tell you where to get them.

**Comment by YoshikiOhtani** [comment]
Thanks a lot, Alessio!

**Comment by aleberti** [comment]
Hi Yoshiki, find attached a file with the links to the remerpped files in PIC. I already checked and interpolation now works fine. To download, just use:
```bash
wget -i remerpped_Crab_files.txt --user=YYYY --password=DDDD
```
using the usual MAGIC credentials.

Please let me know if you have other issues.

[remerpped_Crab_files.txt](https://github.com/cta-observatory/ctapipe_io_magic/files/7839334/remerpped_Crab_files.txt)

**Comment by aleberti** [comment]
FYI, I tried to run `star` over the file `20201214_M1_05093663.007_Y_CrabNebula-W0.40+215.root`. At first it gives the error:

```
Only 1 starguider reports were valid. (Minimum number of valid reports required: 5).
Cannot calibrate the starguider.
Error detected while PostProcessing.
Calculation of image parameters failed.
```

Disabling the use and calibration of starguider, it processes without errors, but for the interpolation it shows:

```
MPointingPosInterpolate: loaded 1 ReportDrive from 14.12.2020 04:20:06.170 to 17.11.1858 00:00:00.000
....
MPointingPosInterpolate: Run time (14.12.2020 04:20:07.000 to 14.12.2020 04:21:12.000 outside range of drive reports  (14.12.2020 04:20:06.170, 17.11.1858 00:00:00.000)
Run defined as short run, problem ignored...
```

which is not good in my opinion. I will try to understand what MARS does in this case.

**Comment by YoshikiOhtani** [comment]
Thanks a lot Alessio, I also succeeded in processing the data that are remerpped with the combined analysis pipeline.

**Comment by aleberti** [comment]
@jsitarek about the interpolation of drive reports, what about doing as done in ctapipe_io_lst? There a specific class is used, which is reading in a file with the drive reports information (https://github.com/cta-observatory/ctapipe_io_lst/blob/master/ctapipe_io_lst/pointing.py). We could do the same, which means processing the subruns from the same run once to get the drive report information and save it in a file, then use this when using the MAGICEventSource.

Or, about the solution you suggested, how exactly would be its implementation?

**Comment by aleberti** [comment]
Ok, I asked also in ctapipe repo: https://github.com/cta-observatory/ctapipe/issues/1821 . Max suggests to do like in `ctapipe_io_lst`, not in the way I suggested, but to give a single file as input (e.g. the first subrun) and then let the event source to find the other subruns belonging to the same run. I will create a branch and work on this. However I think that for the LST analysis school we can keep things as they are now.
