### ISSUE TITLE
No prescaler data in Trigger tree

### ISSUE THREAD

**Issue by YoshikiOhtani** [cta-observatory/ctapipe_io_magic#17]
After fixing the issue #14, I processed some Crab Nebula data and found a weird data file:
/home/yoshiki.ohtani/combined_analysis/real/CrabNebula/2020_12_13/1.magic_cal_to_dl1/data/calibrated/20201214_M2_05093664.015_Y_CrabNebula-W0.40+035.root

The data file doesn't contain not only the prescaler data ("MTriggerPrescFact.fPrescFact") but also the other data in the `Trigger` tree for some reason, which stops the initialization of the MAGICEventSource in `parse_data_info` method. Since there is no corresponding subrun file for M1 data in PIC server (i.e., `M1_05093664.015` file does NOT exist), the data itself is indeed weird, but it seems to be better to decide how to handle such kind of data when it is input in the MAGICEventSource. One solution is simply stops the process, but since the event data are normally stored in `Events` tree, the other solution is to set `None` to `self.is_stereo` and `self.is_sumt` variables.

**Comment by aleberti** [comment]
I fixed this but I preferred to give `self.is_stereo` and `self.is_sumt` the default values True and False respectively.

**Comment by YoshikiOhtani** [comment]
OK thanks
