### ISSUE TITLE
Two functions to read run information?

### ISSUE THREAD

**Issue by YoshikiOhtani** [cta-observatory/ctapipe_io_magic#39]
Now there are two functions to read run information, one from file name (`get_run_info_from_name` function) and the other one from RunHeaders/Events trees (`parse_run_info` function), but I don't see the reason why we keep the former one because all information can be obtained from the trees. And I also see that the current MAGICEventSource first reads the information from file name and later from the trees, and it fails if the file name doesn't follow the convention, even though the necessary information can be obtained from the trees. Could someone clarify the reason, probably @aleberti?

**Comment by aleberti** [comment]
So the first function was the one used until some time ago, then I added the second one. I left the former as a x-check, indeed it is used as such in one test. For the moment I would like to keep it, I have to understand what happens for different datalevels. In particular, for merged MC files at superstar level, I have to check how to extract correctly the information on the run numbers (I do not know if somewhere in the RunHeader the information on which runs were merged is kept).

**Comment by aleberti** [comment]
Anyway, when I see it is not needed anymore, it can be reomoved. or maybe put in a separate submodule, or in magic-cta-pipe, so that one does not need to open the file if the only info needed is the datalevel, the run number or the telescope.
