### ISSUE TITLE
MAGIC positions defined in MAGICEventSource

### ISSUE THREAD

**Issue by YoshikiOhtani** [cta-observatory/ctapipe_io_magic#40]
I think the MAGIC positions defined inside the MAGICEventSource are in the CORSIKA coordinate (x-axis: geomagnetic north):
https://github.com/cta-observatory/ctapipe_io_magic/blob/f6c99d41291fe1b545e9f9e1f5b38354d9931e17/ctapipe_io_magic/__init__.py#L575-L577

Actually I checked that the converted positions to the geographical one are almost consistent with the ones used in sim_telarray simulations (the telescope positions are defined in the geographical one in the corsika_simtel input card.)

However, ctapipe usually requires the parameters defined in the geographical coordinate, and the positions the SubarrayDescription expects is usually the geographical one. We actually convert, for example, MC core positions to the geographical frame:
https://github.com/cta-observatory/ctapipe_io_magic/blob/f6c99d41291fe1b545e9f9e1f5b38354d9931e17/ctapipe_io_magic/__init__.py#L1157-L1166

So I think we should also use the MAGIC positions defined in the geographical coordinate. If we rotate the coordinate by the declination (= -7 deg), the new positions rounded off to two decimal place are

```
# Geographical coordinate:
MAGIC_TEL_POSITIONS = {
    1: u.Quantity([34.99, -24.02, 0], u.m),
    2: u.Quantity([-34.99, 24.02, 0], u.m),
}
```

If everyone agrees, I would like to push a commit, but it would be good if someone could give me some comments on this.

**Comment by aleberti** [comment]
Maybe @jsitarek can comment more on this. I don't know what simtelarray does, looking a bit at the documentation by Konrad it seems that geographical coordinates are used (but I may be wrong). Anyway, since telescope positions are used in some parts of the reconstruction, of course the reference system should be the same between the event source and what ctapipe expects.

**Comment by aleberti** [comment]
Hi, I am slowly coming back to the work after the MAGIC shift and looking at the different issues. @YoshikiOhtani @jsitarek regarding this, should we change the coordinates at the end in `ctapipe_io_magic`?

**Comment by YoshikiOhtani** [comment]
I think we should change but still waiting for Julian's opinion?

**Comment by jsitarek** [comment]
Sorry for a very late feedback on this. 
I confirm most of what it was said above, i.e. the standard MagicSoft simulations are done at [3180.0 -2810.0] [-3180.0  2810.0] w.r.t. magnetic axis, which corresponds (with the rotation angle of -7 deg) to [3498.7, -2401.5] [-3498.7, 2401.5] which is consistent with what Yoshiki wrote above.

corsika settings in LSTProd2 are in geographic coordinates:
TELESCOPE              41.054E2   -79.275E2   0.25E2        10.00E2   # MAGIC-01 (ID=2)
TELESCOPE             -29.456E2   -31.295E2   1.42E2        10.00E2   # MAGIC-02 (ID=3)

when translated to center of both telescopes imply M1 = [3525.5, -2399.0], M2 = [-3525.5, 2399.0], which is matching within ~25cm. The ARRANG angle in this case is -4.84deg, but it is not a problem as long as the geographic coordinates are used.

when I open one of the LSTProd2 files I get:
source.subarray.tel_coords                                                                       
Out[17]: 
<SkyCoord (GroundFrame): (x, y, z) in m
    [( -8.09000015,  77.12999725, 43.        ),
     ( 39.29999924, -62.54999924, 41.25      ),
     (-31.20999908, -14.56999969, 42.41999817)]>

so the same geometrical coordinates are in the corsika input card

so yes, I think the position should be updated (at least for the case when MCs are being processed)

I have more doubts about the other values stored, the core positions, azimuth angles etc.
the core position taken from MC files is defined w.r.t. magnetic North, and a rotation is done in ctapipe_io_magic, so it is saved (hopefully) w.r.t. geographical north - I'm checking with Konrad if this is how it is done for the sim_telarray simulations.

azimuths are much more messy, 
in the general MAGICEventSource that is seems to operate both on data and MCs
https://github.com/cta-observatory/ctapipe_io_magic/blob/f6c99d41291fe1b545e9f9e1f5b38354d9931e17/ctapipe_io_magic/__init__.py#L1157
event.simulation.shower.az for MCs is converted to geographical coordinates

but in MarsCalibratedRun
dictionary is filled with mc_phi directly read from the input first MMcEvt.fPhi which is corsika original definitoin (inversted and w.r.t. magnetic axis)
https://github.com/cta-observatory/ctapipe_io_magic/blob/f6c99d41291fe1b545e9f9e1f5b38354d9931e17/ctapipe_io_magic/__init__.py#L1330

I'm not fully sure about the telescopose pointing Az, but it seems to come from geographical definition.

**Comment by aleberti** [comment]
> event.simulation.shower.az for MCs is converted to geographical coordinates
> but in MarsCalibratedRun dictionary is filled with mc_phi directly read from the input first MMcEvt.fPhi which is corsika original definitoin (inversted and w.r.t. magnetic axis)
> 
> https://github.com/cta-observatory/ctapipe_io_magic/blob/f6c99d41291fe1b545e9f9e1f5b38354d9931e17/ctapipe_io_magic/__init__.py#L1330
> 
> I'm not fully sure about the telescopose pointing Az, but it seems to come from geographical definition.

About the true azimuth for MCs, MMcEvt.fPhi, as written in the MARS docs, is in the CORSIKA frame, so it is extracted as is in MarsCalibratedRun, and then its values are used to fill event.simulation.shower.az, after correction due to the different reference frame. So it should be ok.

For the telescope azimuth, for MCs the MPointingPos branch is read, where everything should be in the drive reference frame, so wrt geographical North. The same applies for real data, where the drive reports are used for interpolation, so final telescope pointings in azimuth are again in the drive reference system.

Regarding the core position, yes, it should be wrt geographical north, but let me know after you hear back from Konrad if we need to change something.

So in principle the geographical system is used for those quantities, but a x-check is always good.

**Comment by YoshikiOhtani** [comment]
Hi @jsitarek, thank you for confirming this.

> when I open one of the LSTProd2 files I get:
> source.subarray.tel_coords
> Out[17]:
> <SkyCoord (GroundFrame): (x, y, z) in m
> [( -8.09000015, 77.12999725, 43. ),
> ( 39.29999924, -62.54999924, 41.25 ),
> (-31.20999908, -14.56999969, 42.41999817)]>


Just in case, I think this coordinate is the one from my LST-1 + MAGIC productions. When I open the one of LST-PROD2 files I get the following:

In [10]: source.subarray.tel_coords
Out[10]: 
<SkyCoord (GroundFrame): (x, y, z) in m
    [( -6.33599997,  60.40499878, 12.5       ),
     ( 41.05400085, -79.27500153, 10.75      ),
     (-29.45600128, -31.29500008, 11.92000008)]>

whose x and y positions are consistent with the input card, which are defined in the geographical coordinate. I noticed that the z positions are shifted to 10.5 m higher, which is not related to this issue, so I will open an issue just in case in the lst-sim-config repository.
