### ISSUE TITLE
Arrival time difference of consecutive trigger events

### ISSUE THREAD

**Issue by YoshikiOhtani** [cta-observatory/ctapipe_io_magic#43]
In order to calculate the total dead time of MAGIC observations, it is necessary to get the arrive time difference of consecutive events. I see that a MAGIC calibrated file has the time differences in the `MRawEvtHeader.fTimeDiff` branch, but currently it is not loaded by the `MAGICEventSource` module. And if we modify the module so as to load the time differences, the default `ArrayEventContainer` doesn't have a space to store them. 

Actually the time differences can be calculated by ourselves if we know the arrive times of events. As far as I understand, the time differences should be calculated by using both cosmic and pedestal events, but the current `MAGICEventSource` reads cosmic and pedestal events separately (depending on the option `use_pedestals`) and so I think we cannot reproduce the values of the `MRawEvtHeader.fTimeDiff` branch.

So there may be two solutions on this:

1. Create a custom timing container which can store a time difference value obtained from the `MRawEvtHeader.fTimeDiff` branch
2. Modify the `MAGICEventSource` to generate both cosmic and pedestal events simultaneously and calculate time differences in the process from calibrated to DL1

I think the solution 2 would be better since customizing the container should be avoided. But any comments or another ideas are very welcome.

**Comment by jsitarek** [comment]
I think it is simpler than this. It is important when *computing* the time difference to take into account all the events (cosmics, pedestals, calibration events), i.e. that it is always computed w.r.t. the previous event, not matter what this event it. But this is already done in MRawEvtHeader.fTimeDiff. When you use this information later on to compute the effective time, it is sufficient to have only the fTimeDiff for the cosmic events, so you can simply add a new field to the MAGICEventSource without modifying the general behaviour

**Comment by YoshikiOhtani** [comment]
Hi @jsitarek, thank you for your comment. I see, so I think you suggest the solution 1. Of course it is easy to load the `MRawEvtHeader.fTimeDiff` values from the file, but what I meant is that we need to modify the event container since it doesn't have a proper space to fill the value for each event, please see the attached picture:
![スクリーンショット 2022-04-19 16 12 11](https://user-images.githubusercontent.com/39613098/163947058-83eba4a9-77ec-4b5e-ad94-1f78c1d7b9db.png)
 
So if everyone agrees, I will create a custom `TelescopeTriggerContainer` and add a parameter space named like `time_diff` so that we can fill the `MRawEvtHeader.fTimeDiff` values to it. Please let me know your thoughts.

**Comment by aleberti** [comment]
Hi @YoshikiOhtani , what @jsitarek suggests is different, and I agree with his solution. Basically you can add a new member/property that is filled in the `__init__` of MAGICEventSource (e.g. call it event_time_diff), so that it is later available if you need to use it or save it in a file.

**Comment by YoshikiOhtani** [comment]
Hi @aleberti, hm, so you mean we create an array of time differences and get the information like this?
```
event_source = MAGICEventSource(path_to_data)
time_diff = event_source.event_time_diff
```
Sorry if I still misunderstand it. But the current module doesn't load the input file in the constructor (`__init__`) but load when executing `_set_active_run` function through `_event_generator`. So you may mean that the array should be saved in a property inside the generator?

**Comment by aleberti** [comment]
Well, true that events are loaded only afterwards, but the ROOT files are opened in the `__init__` 
https://github.com/cta-observatory/ctapipe_io_magic/blob/4e4dd8ee3bf8ad8a974b72806ca66714c96c4130/ctapipe_io_magic/__init__.py#L190
and you can simply read the TTree  `Events/MRawEvtHeader.fTimeDiff` directly after that (maybe with a function). There is no need to do it together with the reading of the events. And yes, abut getting the information, that is exactly what I was thinking about.

**Comment by YoshikiOhtani** [comment]
I see, OK, I agree that it would be the most simplest way to implement. I will make a pull request about this. Thanks!
