### ISSUE TITLE
release with a bugfix?

### ISSUE THREAD

**Issue by jsitarek** [cta-observatory/ctapipe_io_magic#45]
while trying to understand why I cannot reproduce the true impact values from MARS simulations I realized that ctapipe_io_magic had its last release on Jan 17, and there were quite some changes in the meantime. In particular on Feb 1 there was this change:
https://github.com/cta-observatory/ctapipe_io_magic/commit/65187bac3e4c5a6a8148ae490a0633efceb31ee1
mostly refactoring, but it actually also fixed a problem in conversion of the azimuth angle (in the old version 90 deg was added, while it should be 180 deg, as it is done currently). 
However when using magic-cta-pipe, it requires ctapipe_io_magic~0.4.1, i.e. the last tagged version, which still has the bug. 

@aleberti can we make a new release?maybe after merging those changes in the telescope position and focal length

**Comment by aleberti** [comment]
Yes sure, I just merged PR #44. I can work out the new release between today and tomorrow, and change correspondingly in magic-cta-pipe.

**Comment by aleberti** [comment]
New 0.4.2 release available: https://github.com/cta-observatory/ctapipe_io_magic/releases/tag/v0.4.2 and also in PyPI (https://pypi.org/project/ctapipe-io-magic/0.4.2/)
