### ISSUE TITLE
Format of MAGIC timestamps

### ISSUE THREAD

**Issue by aleberti** [cta-observatory/ctapipe_io_magic#8]
Looking at the code from MAGIC+LST1 analysis in https://github.com/cta-observatory/magic-cta-pipe, I realized that Yoshiki uses a custom TriggerContainer to fill custom members millisec and nanosec, since he needs them to have the sufficient precision. This can be solved by merging his branch dev-yoshiki into master and solving the conflicts. For the moment this is fine. For the future we should find a more stable solution without invoking custom containers.

**Comment by YoshikiOhtani** [comment]
Hi Alessio, exactly, I use the modified trigger container which can directly store the "mjd", "millisec" and "nanosec" parameters. The default container can only store one parameter for timestamp, but it loses the precision. Now I have finished the update of the MAGICEventSource to be used in ctapipe v0.12.0 environment, but I still had to modify the trigger container.

**Comment by aleberti** [comment]
Thanks! As I wrote in the PR, you can open a new one, this time from the dev-yoshiki branch to master. I can review that.

**Comment by YoshikiOhtani** [comment]
I have just opened a pull request #12

**Comment by aleberti** [comment]
Closed with #12 and #13.
